const fs=require("fs"),p=require("path"),{execFileSync}=require("child_process");
const ROOT="C:\\MultiAgentSystem\\_Next",OPS=p.join(ROOT,"ops"),CA=p.join(OPS,"coding_agents");
const EXEC=p.join(OPS,"local_executor","fde_local_executor.cjs"),SERVER=p.join(OPS,"local_executor","fde_local_server.cjs"),GUARD=p.join(OPS,"arsenal","phase1","guard.cjs");
const POLICY=p.join(process.env.LOCALAPPDATA||p.join(process.env.USERPROFILE,"AppData","Local"),"FirstDollarEngine","policy","phase1.json");
fs.mkdirSync(CA,{recursive:true});
const stamp=new Date().toISOString().replace(/[:.]/g,"-"),backup=p.join(CA,"backup-"+stamp);fs.mkdirSync(backup,{recursive:true});
for(const f of [EXEC,SERVER,GUARD,POLICY])if(fs.existsSync(f))fs.copyFileSync(f,p.join(backup,p.basename(f)));
const code=String.raw\`const fs=require("fs"),p=require("path"),{execFile}=require("child_process");
const BASE=p.resolve("C:\\\\MultiAgentSystem"),MODEL="qwen3-coder:30b-a3b-q4_K_M",OLLAMA="http://127.0.0.1:11434";
const RUNNABLE=["aider","qwen","opencode"],DISCOVER=["aider","qwen","opencode","openhands","kilo","agy","ollama"];
function obj(v){return v&&typeof v==="object"&&!Array.isArray(v)}function inside(x){const f=p.resolve(x),b=BASE.toLowerCase()+p.sep;return f.toLowerCase().startsWith(b)}
function validate(t){if(!obj(t)||t.action!=="coding_agent"||!obj(t.args))return"invalid_coding_agent_task";const a=t.args;if(!["doctor","run"].includes(a.operation))return"coding_operation_not_allowed";if(a.operation==="doctor")return Object.keys(a).some(k=>k!=="operation")?"unknown_coding_argument":null;if(typeof a.repo!=="string"||!inside(a.repo))return"repo_outside_allowed_root";if(typeof a.prompt_path!=="string"||!inside(a.prompt_path))return"prompt_outside_allowed_root";if(a.agent!=null&&!RUNNABLE.includes(a.agent))return"coding_agent_not_allowed";return Object.keys(a).some(k=>!["operation","repo","prompt_path","agent"].includes(k))?"unknown_coding_argument":null}
function ex(file,args,opt={}){return new Promise(r=>execFile(file,args,{cwd:opt.cwd,windowsHide:true,timeout:opt.timeout||120000,maxBuffer:500000,env:{...process.env,...(opt.env||{})}},(e,so,se)=>r({ok:!e,code:e?.code??0,stdout:String(so||""),stderr:String(se||""),error:e?String(e.message):null})))}
async function where(n){const r=await ex("where.exe",[n]);return r.ok?r.stdout.split(/\\r?\\n/).map(s=>s.trim()).find(Boolean)||null:null}
async function doctor(){const found={},versions={};for(const n of DISCOVER){found[n]=await where(n);if(found[n]){const r=await ex(found[n],["--version"],{timeout:15000});versions[n]=(r.stdout||r.stderr).trim().split(/\\r?\\n/)[0]||null}}let models=[];if(found.ollama){const r=await ex(found.ollama,["list"],{timeout:15000});models=r.ok?r.stdout.split(/\\r?\\n/).slice(1).map(s=>s.trim()).filter(Boolean):[]}return{ok:true,found,versions,models,primary_model:MODEL,runnable:RUNNABLE.filter(n=>found[n])}}
async function runAgent(a){const repo=p.resolve(a.repo),prompt=fs.readFileSync(p.resolve(a.prompt_path),"utf8");if(!prompt.trim())return{ok:false,error:"empty_prompt"};const common=["Work only inside this repository.","Do not control any browser.","Do not access credential stores or secrets.","Make the smallest bounded change.","Run relevant tests before success.","After two failed attempts stop and report SAFE_FAIL.",prompt].join("\\n");const found={};for(const n of RUNNABLE)found[n]=await where(n);const agent=a.agent||RUNNABLE.find(n=>found[n]);if(!agent)return{ok:false,error:"no_local_coding_agent_available",found};let r;if(agent==="aider")r=await ex(found.aider,["--model","ollama_chat/"+MODEL,"--message",common,"--yes-always","--no-gui","--no-browser","--disable-playwright"],{cwd:repo,timeout:1800000,env:{OLLAMA_API_BASE:OLLAMA}});else if(agent==="qwen")r=await ex(found.qwen,["--prompt",common,"--output-format","json"],{cwd:repo,timeout:1800000,env:{OPENAI_API_KEY:"ollama",OPENAI_BASE_URL:OLLAMA+"/v1",OPENAI_MODEL:MODEL,QWEN_MODEL:MODEL}});else{const oc={model:"ollama/"+MODEL,provider:{ollama:{npm:"@ai-sdk/openai-compatible",name:"Ollama (local)",options:{baseURL:OLLAMA+"/v1"},models:{[MODEL]:{name:MODEL}}}}};r=await ex(found.opencode,["run","--format","json","--model","ollama/"+MODEL,common],{cwd:repo,timeout:1800000,env:{OPENCODE_CONFIG_CONTENT:JSON.stringify(oc),OPENCODE_DISABLE_AUTOUPDATE:"true"}})}return{ok:r.ok,agent,model:MODEL,repo,code:r.code,stdout:r.stdout.slice(-200000),stderr:r.stderr.slice(-50000),error:r.error}}
async function run(t){const why=validate(t);if(why)return{ok:false,error:why};try{return t.args.operation==="doctor"?await doctor():await runAgent(t.args)}catch(e){return{ok:false,error:String(e.message||e)}}}
module.exports={validate,run};\`;
fs.writeFileSync(p.join(OPS,"local_executor","coding_agent.cjs"),code);
let e=fs.readFileSync(EXEC,"utf8");if(!e.includes('task.action==="coding_agent"')){const a='else if(task.action==="desktop_action") result=await require(\\'./cua_desktop.cjs\\').run(task);';if(!e.includes(a))throw Error("EXECUTOR_ANCHOR_NOT_FOUND");e=e.replace(a,a+'\\n    else if(task.action==="coding_agent") result=await require(\\'./coding_agent.cjs\\').run(task);');fs.writeFileSync(EXEC,e)}
let g=fs.readFileSync(GUARD,"utf8");if(!g.includes("coding_agent.cjs")){const a="function nativeCheck(task){";if(!g.includes(a))throw Error("GUARD_ANCHOR_NOT_FOUND");g=g.replace(a,a+"\\n  if(task.action==='coding_agent'){ const reason=require('../../local_executor/coding_agent.cjs').validate(task); if(reason) return reason; }");fs.writeFileSync(GUARD,g)}
let s=fs.readFileSync(SERVER,"utf8");if(!s.includes('"coding_agent"')){s=s.replace(/\\["file_write","mkdir","shell","desktop_action"\\]/,'["file_write","mkdir","shell","desktop_action","coding_agent"]');fs.writeFileSync(SERVER,s)}
const j=JSON.parse(fs.readFileSync(POLICY,"utf8"));for(const r of j.rules||[])if(r.id==="routine"&&Array.isArray(r.tools)&&!r.tools.includes("coding_agent"))r.tools.push("coding_agent");fs.writeFileSync(POLICY,JSON.stringify(j,null,2));
for(const f of [p.join(OPS,"local_executor","coding_agent.cjs"),EXEC,SERVER,GUARD])execFileSync(process.execPath,["--check",f],{windowsHide:true,stdio:"pipe"});
fs.writeFileSync(p.join(CA,"BOOTSTRAP_READY.json"),JSON.stringify({ok:true,backup,timestamp:new Date().toISOString()},null,2));
console.log(JSON.stringify({ok:true,backup,reload_required:true}));